name: device_packages_android
description: Android implementation of [device_packages] plugin.
version: 0.1.0

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  plugin:
    implements: device_packages
    platforms:
      android:
        package: io.alexrintt.device_packages_android
        pluginClass: DevicePackagesAndroidPlugin
